"""Provide InterSiteMatchedInterpolation transformer."""

import itertools
import warnings
from typing import Any, Literal

import numpy as np
import structlog
from imblearn.base import SamplerMixin
from numpy.typing import ArrayLike, NDArray
from sklearn.base import BaseEstimator
from sklearn.utils import check_random_state
from sklearn.utils.validation import check_array, check_X_y

from uniharmony.interpolation._utils import (
    sites_sanity_checks,
    validate_covariates,
)


__all__ = ["InterSiteMatchedInterpolation"]

logger = structlog.get_logger()


class InterSiteMatchedInterpolation(SamplerMixin, BaseEstimator):
    """Inter-Site Matched Interpolation (ISMI) Harmonization.

    This sampler performs **cross-site matched interpolation** to reduce spurious
    correlations between site and class labels by generating synthetic
    samples from matched samples across different sites.

    The algorithm iterates through all unique site pairs. The matching strategy
    prioritizes target value matching first, then refines matches using
    categorical and continuous covariates.

    The interpolation takes a base sample from one site and a matched sample from another (target) site.
    A synthetic sample is generated by interpolating between the base and target samples using a randomly sampled alpha value.
    The alpha parameter controls how close the synthetic sample is to the base or target site, allowing a flexible interpolation.

    By matching the samples with similar target values and covariates across sites,
    ISMI creates synthetic samples that mantains the the underlying data distribution while reducing site-specific biases.

    Parameters
    ----------
    alpha : float or tuple[float, float], optional (default 0.3)
        Interpolation weight(s). If a float, all interpolations use this
        constant alpha value. If a tuple ``(min, max)``, alpha is sampled
        uniformly from ``[min, max]`` for each interpolation.
        Alpha must be in the range [0, 1]. Interpretation:

        - ``alpha = 0.0``: synthetic sample equals base site sample
        - ``alpha = 0.5``: synthetic sample is midpoint between sites
        - ``alpha = 1.0``: synthetic sample equals target site sample

        Default is 0.3 to keep synthetic samples closer to the base site.

    target_tolerance : float or None, optional (default None)
        Tolerance for target value matching. For classification tasks, this
        should be 0 or None (exact match required). For regression tasks, allows
        matching targets within ``±target_tolerance``.
        If ``None``, exact matching is required.
        target_tolerance should be in the same units as the target variable (e.g., years for age prediction).

    covariate_tolerance : array-like, shape (n_continuous,), optional (default None)
        Maximum allowed absolute difference for continuous covariate matching.
        Must have one value per continuous covariate column.
        If ``None``, exact matching is required (covariate_tolerance=0).
        Covariate tolerance should be in the same units as the corresponding covariate (e.g., years for age).

    k : int or {"max", "average"}, optional (default 1)
        Number of matches to use for interpolation:
        - ``int >= 1``: Use exactly ``k`` matches per sample. If fewer matches
          are found, a warning is issued and all available matches are used.
        - ``"max"``: Use all available matches for each sample.
        - ``"average"``: Interpolate the base sample with the average of all
          matched samples from the target site.

    mode : {"pairwise", "base_to_others"}, optional (default "pairwise")
        Interpolation mode:
        - ``"pairwise"``: Generate all unique site pairs. For ``n`` sites,
          this produces ``n*(n-1)/2`` pairs.
        - ``"base_to_others"``: Use each site as base once against all other
          sites combined. This mode only works with k="average",
          as the avergage of all matches for all sites is used as target sample.

    concatenate : bool, optional (default True)
        If ``True``, the output dataset includes both original and synthetic samples.
        If ``False``, only synthetic samples are returned.

    random_state : int or np.random.RandomState or None, optional (default None)
        The seed of the pseudo random number generator for reproducibility.

    Attributes
    ----------
    interpolator_ : SamplerMixin
        The fitted interpolator instance.
    sites_resampled_ : ndarray of shape (n_samples_new,)
        Site labels for the resampled dataset (original + synthetic).
    unmatched_samples_ : dict
        Dictionary tracking unmatched samples per direction. Keys are tuples
        indicating the interpolation direction (source_site, target_site).
        For ``base_to_others`` mode, target is ``"others"``. Values are counts
        of source samples that found no valid matches.

    See Also
    --------
    IntraSiteInterpolation : Site-wise class balancing without cross-site
        interpolation.

    Notes
    -----
    **Alpha Reversal Strategy**

    For computational efficiency, the algorithm processes each unique site
    pair only once. For a pair (SiteA, SiteB):

    - Forward (A→B): samples alpha from ``[alpha_min, alpha_max]``
    - Reverse (B→A): samples alpha from ``[1-alpha_max, 1-alpha_min]``

    This mathematically emulates running B→A with the original alpha range
    but avoids redundant matching operations.

    **Matching Hierarchy**

    Matches are determined in the following priority order:

    1. **Target value**: Must match exacly for categorical variables
                         or within ``target_tolerance`` if target is a contunuous variable.
    2. **Categorical covariates**: Exact match required, checked in column
       order (first column must match, then second, etc.)
    3. **Continuous covariates**: Must be within ``covariate_tolerance`` for each column

    If no samples in the target site satisfy all criteria, the source sample
    is counted as unmatched and no synthetic sample is generated.

    Examples
    --------
    >>> import numpy as np
    >>> from uniharmony.interpolation import InterSiteMatchedInterpolation
    >>>
    >>> # Generate sample data with 3 sites
    >>> rng = np.random.RandomState(42)
    >>> X = rng.randn(150, 10)
    >>> y = rng.randint(0, 2, 150)
    >>> sites = np.array(["A"] * 50 + ["B"] * 50 + ["C"] * 50)
    >>>
    >>> # Define covariates for matching
    >>> categorical_covariate = np.array([["M"], ["F"]] * 75)  # Sex
    >>> continuous_covariate = rng.randint(20, 80, (150, 1))  # Age
    >>> tolerance = np.array([5.0])  # ±5 years tolerance
    >>>
    >>> # Create interpolator with pairwise mode and k=2 matches
    >>> ismi = InterSiteMatchedInterpolation(
    ...     alpha=(0.2, 0.4),
    ...     tolerance=tolerance,
    ...     k=2,
    ...     mode="pairwise",
    ...     random_state=42,
    ... )
    >>>
    >>> # Generate harmonized dataset
    >>> X_res, y_res = ismi.fit_resample(
    ...     X, y,
    ...     sites=sites,
    ...     categorical_covariate=categorical_covariate,
    ...     continuous_covariate=continuous_covariate,
    ... )
    >>>
    >>> # Check unmatched samples
    >>> print(ismi.unmatched_samples_)
    {('A', 'B'): 3, ('B', 'A'): 2, ('A', 'C'): 5, ...}

    References
    ----------
    .. [1] Nieto, N., et al. (2026). Data harmonizing via interpolation applied
       to brain age prediction. *Springer Nature*.
       https://doi.org/10.1007/s44248-026-00100-7

    """

    def __init__(
        self,
        alpha: float | tuple[float, float] | list[float] = 0.3,
        target_tolerance: float | None = None,
        covariate_tolerance: ArrayLike | None = None,
        k: int | Literal["max", "average"] = 1,
        mode: Literal["pairwise", "base_to_others"] = "pairwise",
        *,
        concatenate: bool = True,
        random_state: int | np.random.RandomState | None = None,
    ) -> None:
        self.alpha = alpha
        self.target_tolerance = target_tolerance
        self.covariate_tolerance = covariate_tolerance
        self.k = k
        self.mode = mode
        self.concatenate = concatenate
        self.random_state = random_state

    def _validate_init_params(self) -> None:
        """Validate constructor parameters."""
        # Validate alpha
        if isinstance(self.alpha, (int, float)):
            alpha_val = float(self.alpha)
            if not (0 < alpha_val < 1):
                raise ValueError(f"alpha={self.alpha} outside (0, 1)")
            self.alpha_min_ = alpha_val
            self.alpha_max_ = alpha_val

        elif isinstance(self.alpha, (tuple, list)) and len(self.alpha) == 2:
            a_min, a_max = self.alpha
            if not isinstance(a_min, (int, float)) or not isinstance(a_max, (int, float)):
                raise ValueError(f"alpha must be float or tuple (min, max), got {self.alpha}")
            a_min, a_max = float(a_min), float(a_max)
            if not (0 < a_min < a_max < 1):
                raise ValueError(f"alpha must satisfy 0 < min < max < 1, got {self.alpha}")
            self.alpha_min_ = a_min
            self.alpha_max_ = a_max
        else:
            raise ValueError(f"alpha must be float or tuple (min, max), got {self.alpha}")

        # Validate k
        if isinstance(self.k, str):
            k_lower = self.k.lower()
            if k_lower not in ("max", "average"):
                raise ValueError(f"k must be int >= 1, 'max', or 'average', got '{self.k}'")
            self.k = k_lower
        else:
            if int(self.k) < 1:
                raise ValueError(f"k must be >= 1, got {self.k}")
            self.k = int(self.k)

        # Force average mode for base_to_others
        if self.mode == "base_to_others" and self.k != "average":
            logger.warning("mode='base_to_others' requires k='average', overriding")
            self.k = "average"

    def fit_resample(
        self,
        X: ArrayLike,
        y: ArrayLike,
        sites: ArrayLike,
        *,
        categorical_covariate: ArrayLike | None = None,
        continuous_covariate: ArrayLike | None = None,
        allow_nan=False,
    ) -> tuple[NDArray[np.float64], NDArray[Any]]:
        """Fit and resample using cross-site matched interpolation.

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
            Feature matrix containing input samples.
        y : array-like of shape (n_samples,)
            Target values. Can be integer labels (classification) or
            continuous values (regression).
        sites : array-like of shape (n_samples,)
            Site or domain identifiers for each sample. Resampling is
            performed between different sites.
        categorical_covariate : array-like of shape (n_samples, n_categorical), default=None
            Categorical covariates used for hierarchical matching (e.g., sex,
            diagnosis group). Matching proceeds in column order: the first
            column must match exactly, then the second, etc.
        continuous_covariate : array-like of shape (n_samples, n_continuous), default=None
            Continuous covariates used for matching after categorical
            matching (e.g., age, education years). Matches must be within
            ``tolerance`` for each column.
        allow_nan : bool, default=None
            If allow continuos and categorical covariates to present NaN or not

        Returns
        -------
        X_resampled : ndarray of shape (n_samples_new, n_features)
            The feature matrix after cross-site interpolation, containing both
            original and synthetic samples.
        y_resampled : ndarray of shape (n_samples_new,)
            The corresponding targets after resampling.

        Site labels for the resampled dataset are stored in the attribute ``sites_resampled_``

        Raises
        ------
        ValueError
            If input arrays have incompatible shapes, if fewer than two unique
            sites are present, if covariates contain invalid values, or if
            parameters are inconsistent.

        """
        # Validate parameters immediately (sklearn convention allows basic validation)
        self._validate_init_params()
        # Validate inputs
        X_arr, y_arr, sites_arr, cat_cov, cont_cov = self._validate_inputs(
            X, y, sites, categorical_covariate, continuous_covariate, allow_nan
        )

        # Initialize tracking
        self.unmatched_samples_: dict[tuple[Any, Any], int] = {}
        self._unique_sites = np.unique(sites_arr)
        self._n_sites = len(self._unique_sites)

        if self._n_sites < 2:
            raise ValueError(f"Need at least 2 sites, got {self._n_sites}")

        # Setup parameters
        self.random_state_ = check_random_state(self.random_state)

        self._log_configuration(cat_cov, cont_cov)

        # Generate samples
        synthetic_X, synthetic_y, synthetic_sites = self._generate_samples(X_arr, y_arr, sites_arr, cat_cov, cont_cov)

        # Combine results
        if synthetic_X:
            if self.concatenate:
                X_out = np.vstack([X_arr, *synthetic_X])
                y_out = np.concatenate([y_arr, *synthetic_y])
                sites_out = np.concatenate([sites_arr, *synthetic_sites])
            else:
                X_out = np.vstack(synthetic_X)
                y_out = np.concatenate(synthetic_y)
                sites_out = np.concatenate(synthetic_sites)
        else:
            X_out, y_out, sites_out = X_arr, y_arr, sites_arr

        self.sites_resampled_ = sites_out

        self._log_completion(y_arr, synthetic_y)

        return X_out, y_out

    def _validate_inputs(
        self,
        X: ArrayLike,
        y: ArrayLike,
        sites: ArrayLike,
        categorical_covariate: ArrayLike | None,
        continuous_covariate: ArrayLike | None,
        allow_nan: bool = False,
    ) -> tuple[
        NDArray[np.float64],
        NDArray[Any],
        NDArray[Any],
        NDArray[Any] | None,
        NDArray[np.float64] | None,
    ]:
        """Validate and convert input arrays."""
        X_arr, y_arr = check_X_y(X, y)
        sites_arr = check_array(sites, ensure_2d=False, dtype=None)

        # Wrap sites_sanity_checks to match expected error message
        try:
            sites_sanity_checks(X_arr, sites_arr)
        except ValueError as e:
            if "At least two sites required" in str(e):
                raise ValueError(f"Need at least 2 sites, got {len(np.unique(sites_arr))}") from e
            raise

        cat_cov, cont_cov, cov_tol = validate_covariates(
            X_arr.shape[0],
            categorical_covariate,
            continuous_covariate,
            self.covariate_tolerance,
            allow_nan=allow_nan,
        )

        self.covariate_tolerance_ = cov_tol
        self._problem_type = "classification" if y_arr.dtype.kind in "biu" else "regression"

        # Set default target_tolerance for regression if not specified
        if self._problem_type == "regression" and self.target_tolerance is None:
            y_range = np.ptp(y_arr)
            self.target_tolerance_ = y_range * 0.1 if y_range > 0 else 1.0
        else:
            self.target_tolerance_ = self.target_tolerance

        return X_arr, y_arr, sites_arr, cat_cov, cont_cov

    def _log_configuration(
        self,
        cat_cov: NDArray[Any] | None,
        cont_cov: NDArray[np.float64] | None,
    ) -> None:
        """Log setup information."""
        n_pairs = self._n_sites * (self._n_sites - 1) // 2
        alpha_str = (
            f"constant={self.alpha_min_}"
            if self.alpha_min_ == self.alpha_max_
            else f"uniform[{self.alpha_min_}, {self.alpha_max_}]"
        )

        logger.info(f"[ISMI] Mode: {self.mode}")
        logger.info(f"[ISMI] Sites: {self._unique_sites} ({self._n_sites} sites, {n_pairs} pairs)")
        logger.info(f"[ISMI] Alpha: {alpha_str}")

        if self.k == "average":
            logger.info("[ISMI] Behavior: average across all matches")
        elif self.k == "max":
            logger.info("[ISMI] Behavior: use all matches")
        else:
            logger.info(f"[ISMI] Behavior: k={self.k} matches per sample")

        logger.info(f"[ISMI] Target tolerance: {self.target_tolerance_}")
        if cat_cov is not None:
            logger.info(f"[ISMI] Categorical covariates: {cat_cov.shape[1]}")
        if cont_cov is not None:
            tol_str = f" (tol: {self.covariate_tolerance_})" if self.covariate_tolerance_ is not None else ""
            logger.info(f"[ISMI] Continuous covariates: {cont_cov.shape[1]}{tol_str}")

    def _log_completion(
        self,
        y_orig: NDArray[Any],
        synthetic_y: list[NDArray[Any]],
    ) -> None:
        """Log completion statistics."""
        n_orig = len(y_orig)
        n_synth = sum(len(s) for s in synthetic_y)
        n_unmatched = sum(self.unmatched_samples_.values())
        increase = (n_synth / n_orig * 100) if n_orig > 0 else 0.0

        logger.info(
            f"[ISMI] Complete: {n_orig} original + {n_synth} synthetic "
            f"= {n_orig + n_synth} total ({increase:.1f}% increase), "
            f"{n_unmatched} unmatched"
        )

    def _generate_samples(
        self,
        X: NDArray[np.float64],
        y: NDArray[Any],
        sites: NDArray[Any],
        cat_cov: NDArray[Any] | None,
        cont_cov: NDArray[np.float64] | None,
    ) -> tuple[
        list[NDArray[np.float64]],
        list[NDArray[Any]],
        list[NDArray[Any]],
    ]:
        """Generate synthetic samples."""
        if self.mode == "pairwise":
            return self._generate_pairwise(X, y, sites, cat_cov, cont_cov)
        return self._generate_base_to_others(X, y, sites, cat_cov, cont_cov)

    def _generate_pairwise(
        self,
        X: NDArray[np.float64],
        y: NDArray[Any],
        sites: NDArray[Any],
        cat_cov: NDArray[Any] | None,
        cont_cov: NDArray[np.float64] | None,
    ) -> tuple[list[NDArray[np.float64]], list[NDArray[Any]], list[NDArray[Any]]]:
        """Generate samples for all site pairs."""
        all_X: list[NDArray[np.float64]] = []
        all_y: list[NDArray[Any]] = []
        all_sites: list[NDArray[Any]] = []

        pairs = list(itertools.combinations(self._unique_sites, 2))

        logger.info(f"[ISMI] Processing {len(pairs)} pairs")

        for s1, s2 in pairs:
            m1 = sites == s1
            m2 = sites == s2

            X1, y1 = X[m1], y[m1]
            X2, y2 = X[m2], y[m2]
            c1 = cat_cov[m1] if cat_cov is not None else None
            c2 = cat_cov[m2] if cat_cov is not None else None
            v1 = cont_cov[m1] if cont_cov is not None else None
            v2 = cont_cov[m2] if cont_cov is not None else None

            logger.info(f"[ISMI] Pair: {s1} ({len(X1)}) ↔ {s2} ({len(X2)})")

            # Forward: s1 → s2
            matches_1to2 = _find_matches(y1, y2, c1, c2, v1, v2, self.target_tolerance_, self.covariate_tolerance_)
            X_synth_1, y_synth_1, n_un_1 = self._interpolate(X1, y1, X2, y2, matches_1to2, self.alpha_min_, self.alpha_max_)
            self.unmatched_samples_[(s1, s2)] = n_un_1

            # Reverse: s2 → s1 (with reversed alpha)
            matches_2to1 = _reverse_matches(matches_1to2, len(X2))
            rev_min, rev_max = 1.0 - self.alpha_max_, 1.0 - self.alpha_min_
            X_synth_2, y_synth_2, n_un_2 = self._interpolate(X2, y2, X1, y1, matches_2to1, rev_min, rev_max)
            self.unmatched_samples_[(s2, s1)] = n_un_2

            # Collect
            if X_synth_1.size > 0:
                all_X.append(X_synth_1)
                all_y.append(y_synth_1)
                all_sites.append(np.full(len(y_synth_1), s1))

            if X_synth_2.size > 0:
                all_X.append(X_synth_2)
                all_y.append(y_synth_2)
                all_sites.append(np.full(len(y_synth_2), s2))

            total = len(y_synth_1) + len(y_synth_2)
            logger.info(f"[ISMI]   Generated {total} samples ({n_un_1 + n_un_2} unmatched)")

        return all_X, all_y, all_sites

    def _generate_base_to_others(
        self,
        X: NDArray[np.float64],
        y: NDArray[Any],
        sites: NDArray[Any],
        cat_cov: NDArray[Any] | None,
        cont_cov: NDArray[np.float64] | None,
    ) -> tuple[list[NDArray[np.float64]], list[NDArray[Any]], list[NDArray[Any]]]:
        """Generate samples for each site vs all others."""
        all_X: list[NDArray[np.float64]] = []
        all_y: list[NDArray[Any]] = []
        all_sites: list[NDArray[Any]] = []

        for base_site in self._unique_sites:
            base_mask = sites == base_site
            other_mask = ~base_mask

            X_base, y_base = X[base_mask], y[base_mask]
            X_other, y_other = X[other_mask], y[other_mask]

            c_base = cat_cov[base_mask] if cat_cov is not None else None
            c_other = cat_cov[other_mask] if cat_cov is not None else None
            v_base = cont_cov[base_mask] if cont_cov is not None else None
            v_other = cont_cov[other_mask] if cont_cov is not None else None

            logger.info(f"[ISMI] {base_site} ({len(X_base)}) → others ({len(X_other)})")

            matches = _find_matches(
                y_base, y_other, c_base, c_other, v_base, v_other, self.target_tolerance_, self.covariate_tolerance_
            )
            X_synth, y_synth, n_un = self._interpolate(
                X_base, y_base, X_other, y_other, matches, self.alpha_min_, self.alpha_max_
            )
            self.unmatched_samples_[(base_site, "others")] = n_un

            if X_synth.size > 0:
                all_X.append(X_synth)
                all_y.append(y_synth)
                all_sites.append(np.full(len(y_synth), base_site))

            logger.info(f"[ISMI]   Generated {len(y_synth)} samples ({n_un} unmatched)")

        return all_X, all_y, all_sites

    def _interpolate(
        self,
        X_src: NDArray[np.float64],
        y_src: NDArray[Any],
        X_dst: NDArray[np.float64],
        y_dst: NDArray[Any],
        matches: list[list[int]],
        alpha_min: float,
        alpha_max: float,
    ) -> tuple[NDArray[np.float64], NDArray[Any], int]:
        """Generate synthetic samples from matches."""
        n_src = len(X_src)

        if n_src == 0 or len(X_dst) == 0:
            return np.array([]).reshape(0, X_src.shape[1] if X_src.size > 0 else 0), np.array([]), n_src

        # Find matched/unmatched
        has_match = np.array([len(m) > 0 for m in matches])
        n_unmatched = n_src - int(np.sum(has_match))
        matched_idx = np.where(has_match)[0]

        if len(matched_idx) == 0:
            return np.array([]).reshape(0, X_src.shape[1]), np.array([]), n_unmatched

        # Sample alphas
        n_matched = len(matched_idx)
        if alpha_min == alpha_max:
            alphas = np.full(n_matched, alpha_min)
        else:
            alphas = self.random_state_.uniform(alpha_min, alpha_max, n_matched)

        # Dispatch to appropriate method
        if self.k == "average":
            X_synth, y_synth = self._interp_average(X_src, y_src, X_dst, y_dst, matches, matched_idx, alphas)

        elif self.k == "max":
            X_synth, y_synth = self._interp_max(X_src, y_src, X_dst, y_dst, matches, matched_idx, alphas)

        else:
            X_synth, y_synth = self._interp_k(X_src, y_src, X_dst, y_dst, matches, matched_idx, alphas, int(self.k))

        return X_synth, y_synth, n_unmatched

    def _interp_average(
        self,
        X_src: NDArray[np.float64],
        y_src: NDArray[Any],
        X_dst: NDArray[np.float64],
        y_dst: NDArray[Any],
        matches: list[list[int]],
        matched_idx: NDArray[np.int64],
        alphas: NDArray[np.float64],
    ) -> tuple[NDArray[np.float64], NDArray[Any]]:
        """Interpolate to average of all matches."""
        X_m = X_src[matched_idx]
        y_m = y_src[matched_idx]

        # Average of destinations for each source
        X_avg = np.array([np.mean(X_dst[matches[i]], axis=0) for i in matched_idx])

        X_synth = X_m + alphas[:, np.newaxis] * (X_avg - X_m)

        if self._problem_type == "classification":
            y_synth = y_m
        else:
            y_avg = np.array([np.mean(y_dst[matches[i]]) for i in matched_idx])
            y_synth = y_m + alphas * (y_avg - y_m)

        return X_synth, y_synth

    def _interp_max(
        self,
        X_src: NDArray[np.float64],
        y_src: NDArray[Any],
        X_dst: NDArray[np.float64],
        y_dst: NDArray[Any],
        matches: list[list[int]],
        matched_idx: NDArray[np.int64],
        alphas: NDArray[np.float64],
    ) -> tuple[NDArray[np.float64], NDArray[Any]]:
        """Interpolate to each match individually."""
        src_exp: list[int] = []
        dst_exp: list[int] = []
        alpha_exp: list[float] = []

        for idx, src_i in enumerate(matched_idx):
            for dst_j in matches[src_i]:
                src_exp.append(src_i)
                dst_exp.append(dst_j)
                alpha_exp.append(alphas[idx])

        src_arr = np.array(src_exp)
        dst_arr = np.array(dst_exp)
        alpha_arr = np.array(alpha_exp)

        X_s = X_src[src_arr]
        X_d = X_dst[dst_arr]
        X_synth = X_s + alpha_arr[:, np.newaxis] * (X_d - X_s)

        if self._problem_type == "classification":
            y_synth = y_src[src_arr]
        else:
            y_s = y_src[src_arr]
            y_d = y_dst[dst_arr]
            y_synth = y_s + alpha_arr * (y_d - y_s)

        return X_synth, y_synth

    def _interp_k(
        self,
        X_src: NDArray[np.float64],
        y_src: NDArray[Any],
        X_dst: NDArray[np.float64],
        y_dst: NDArray[Any],
        matches: list[list[int]],
        matched_idx: NDArray[np.int64],
        alphas: NDArray[np.float64],
        k: int,
    ) -> tuple[NDArray[np.float64], NDArray[Any]]:
        """Interpolate to k randomly selected matches."""
        src_exp: list[int] = []
        dst_exp: list[int] = []
        alpha_exp: list[float] = []

        for idx, src_i in enumerate(matched_idx):
            n_match = len(matches[src_i])
            if n_match < k:
                warnings.warn(
                    f"Sample has {n_match} matches but k={k} requested, using all",
                    UserWarning,
                    stacklevel=3,
                )
            n_use = min(k, n_match)
            selected = self.random_state_.choice(matches[src_i], size=n_use, replace=False)

            for dst_j in selected:
                src_exp.append(src_i)
                dst_exp.append(dst_j)
                alpha_exp.append(alphas[idx])

        src_arr = np.array(src_exp)
        dst_arr = np.array(dst_exp)
        alpha_arr = np.array(alpha_exp)

        X_s = X_src[src_arr]
        X_d = X_dst[dst_arr]
        X_synth = X_s + alpha_arr[:, np.newaxis] * (X_d - X_s)

        if self._problem_type == "classification":
            y_synth = y_src[src_arr]
        else:
            y_s = y_src[src_arr]
            y_d = y_dst[dst_arr]
            y_synth = y_s + alpha_arr * (y_d - y_s)

        return X_synth, y_synth

    def _fit_resample(self, X: ArrayLike, y: ArrayLike, **params: Any) -> None:
        """For SamplerMixin compatibility."""
        pass


def _find_matches(
    y_src: NDArray[Any],
    y_dst: NDArray[Any],
    cat_src: NDArray[Any] | None,
    cat_dst: NDArray[Any] | None,
    cont_src: NDArray[np.float64] | None,
    cont_dst: NDArray[np.float64] | None,
    target_tol: float | None,
    cov_tol: NDArray[np.float64] | None,
) -> list[list[int]]:
    """Find matches with target priority."""
    n_src = len(y_src)

    # Target match
    if target_tol is None or target_tol == 0:
        match = y_src[:, np.newaxis] == y_dst[np.newaxis, :]
    else:
        match = np.abs(y_src[:, np.newaxis] - y_dst[np.newaxis, :]) <= target_tol

    # Categorical match
    if cat_src is not None and cat_dst is not None:
        for c in range(cat_src.shape[1]):
            match &= cat_src[:, c][:, np.newaxis] == cat_dst[:, c][np.newaxis, :]

    # Continuous match
    if cont_src is not None and cont_dst is not None and cov_tol is not None:
        for c in range(cont_src.shape[1]):
            diff = np.abs(cont_src[:, c][:, np.newaxis] - cont_dst[:, c][np.newaxis, :])
            match &= diff <= cov_tol[c]

    return [np.where(match[i])[0].tolist() for i in range(n_src)]


def _reverse_matches(matches_fwd: list[list[int]], n_dst: int) -> list[list[int]]:
    """Reverse match list direction."""
    rev: list[list[int]] = [[] for _ in range(n_dst)]
    for src_i, dst_list in enumerate(matches_fwd):
        for dst_j in dst_list:
            rev[dst_j].append(src_i)
    return rev
