[project]
site_name = "UniHarmony"
site_url = "https://github.com/N-Nieto/UniHarmony"
repo_url = "https://github.com/N-Nieto/UniHarmony"
repo_name = "N-Nieto/UniHarmony"
nav = [
  {"Home" = "index.md"},
  {"Getting Started" = "getting_started.md"},
  {"Utilities" = [
      {"Simulate Multisite Data" = "simulate_multisite_data.md"},
      {"Load MAREos Datasets" = "load_mareos_datasets.md"},
  ]},
  {"Methods" = [
      {"ComBat-based harmonization" = [
          {"Overview" = "combat_based_harmonization.md"},
          {"ComBat / neuroComBat" = "combat_based/combat.md"},
          {"ComBat-GAM (neuroHarmonize)" = "combat_based/combat_gam.md"},
          {"CovBat" = "combat_based/covbat.md"},
          {"Longitudinal ComBat" = "combat_based/longcombat.md"},
          {"Neuroharmony" = "combat_based/neuroharmony.md"},
          {"DeepComBat" = "combat_based/deepcombat.md"},
          {"BARTharmonization" = "combat_based/bartharmonize.md"},
          {"PrettYharmonize" = "combat_based/prettyharmony.md"}
      ]},
      {"Interpolation" = [
        {"Overview" = "interpolation.md"},
        {"Inter Site Matched Interpolation" = "interpolation_based/inter_site_matched_interpolation.md"},
        {"Intra Site Interpolation" = "interpolation_based/intra_site_interpolation.md"}
      ]}
  ]},
  {"Examples" = [
      {"Load MAREoS" = "examples/load_mareos_example.md"},
      {"Generate mutlisite data" = "examples/generate_multisite_data_example.md"},
      {"Multisite data characterization" = "examples/multisite_data_characterization_example.md"},
      {"Intra Site Interpolation for binary classification" = "examples/interpolation-based/ISI_binary_classification_example.md"},
      {"Intra Site Interpolation for multiclass classification" = "examples/interpolation-based/ISI_multiclass_classification_example.md"},
      {"neuroComBat for binary classification" = "examples/neuroComBat_binary_classification_example.md"},
      {"neuroComBat with MAREoS" = "examples/neuroComBat_in_MAREoS.md"},
  ]},
  {"API Reference" = [
      {"ComBat" = [
          {"NeuroComBat" = "api/combat/neurocombat.md"},
      ]},
      {"Interpolation" = [
          {"IntraSiteInterpolation" = "api/interpolation/intrasite.md"},
      ]},
      {"Utilities" = "api/utils.md"},
  ]},
]
extra_javascript = [
    "javascripts/mathjax.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js"
]

[project.theme]
features = [
    "content.code.copy",
    "content.code.select",
    "navigation.top",
    "content.footnote.tooltips",
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.footnotes]

[project.markdown_extensions.toc]
permalink = true

[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "numpy"
inherited_members = true
show_source = true
