name: Documentation Request
description: Request to enhance or modify the documentation
title: "[DOC]: "
labels: ["documentation", "triage"]
assignees:
  - nnieto
body:
  - type: markdown
    attributes:
      value: |
        Fill in this form if you want to suggest a modification to the documentation.
  - type: textarea
    id: description
    attributes:
      label: Which element of the documentation do you want to modify and why?
      description: |
        Please include a brief description, including the motivation, and why we should change or add this in uniharmony's documentation.
      placeholder: If a relevant citation or acknowledgment is needed, please include it as well.
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Anything else to say?
      description:
      placeholder: ...
