name: Feature Request
description: Request to include a new feature
title: "[ENH]: "
labels: ["enhancement", "triage"]
assignees:
  - nnieto
  - synchon
body:
  - type: markdown
    attributes:
      value: |
        Fill in this form if you want uniharmony to include a new feature. If you want to include a new model implementation, please fill in the model implementation request form instead.
  - type: textarea
    id: description
    attributes:
      label: Which feature do you want to include?
      description: |
        Please include a complete description, including the motivation, description, and why we should include it in uniharmony.
      placeholder: With more information, we can better understand the need for this feature and how to implement it!
    validations:
      required: true
  - type: textarea
    id: behaviour
    attributes:
      label: How do you imagine this integrated in uniharmony?
      description: |
        Please provide your idea on how this can be implemented. How would you like to use uniharmony?
      placeholder: Help us make it easy for you!
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Do you have a sample code that implements this outside of uniharmony?
      description: |
        If you manage to have an idea on how to implement it, please copy and paste your implementation code or pseudo-code here. You can also post a link to a gist or github repository.
      render: shell
  - type: textarea
    id: extra
    attributes:
      label: Anything else to say?
      description:
      placeholder: ...
