name: Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install -y \
          git-annex
      - name: Configure Git for DataLad
        run: |
          git config --global user.email "runner@github.com"
          git config --global user.name "GitHub Runner"
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v7
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -e .[docs]
      - name: Build docs
        run: |
          cd docs
          make html
          cd ..
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build
