name: Deploy PR doc preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  pull-requests: write
  contents: write

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        if: github.event.action != 'closed'
        with:
          python-version: 3.x
      - name: Install zensical and build docs
        if: github.event.action != 'closed'
        run: |
            pip install zensical
            zensical build --clean
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
            source-dir: ./site/
            preview-branch: gh-pages
            qr-code: true
